name: CI for ChatBOTPFE

# Trigger the workflow on pushes and pull requests to the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The job will run on the latest Ubuntu environment.
    runs-on: ubuntu-latest

    # Run the job against multiple Python versions.
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10","3.11" ]

    steps:
      # 1. Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python using the matrix value.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Upgrade pip and install dependencies.
      - name: Install Dependencies
        run: |

          pip install -r requirements.txt

      # 4. Lint Python code in the BACK folder.
      - name: Lint Python Code
        run: |
          pip install flake8
          flake8 BACK/

      # 5. Run the main script with a simple argument to check it executes.
      - name: Run main.py
        run: python ./BACK/main.py --qa ./BACK/datasetsqa/qa_AssuranceAuto.json
