name: CI for ChatBOTPFE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          
          pip install -r requirements.txt

      # Install Ollama on the GitHub runner
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &  # Run Ollama as a background process

      # Wait for Ollama to start
      - name: Check if Ollama is Running
        run: |
          sleep 5  # Wait a few seconds for Ollama to start
          curl -X POST http://localhost:11434/api/tags || exit 1

      # Pull the required Ollama model
      - name: Pull Ollama Model
        run: |
          ollama pull phi3

      # Run main application with Ollama backend
      - name: Run main.py
        run: python ./BACK/main.py --qa ./BACK/datasets/qa/qa_AssuranceAuto.json
